/*
 * Copyright (c) 2018. Punch Cyber Analytics Group
 * All rights reserved.
 *
 * NOTICE: All information contained herein is the property of Punch Cyber Analytics Group.
 * The intellectual and technical concepts contained herein are proprietary to Punch Cyber
 * Analytics Group and may be covered by Patents and/or Patents in process in multiple
 * jurisdictions and as such, are protected by trade secret and/or copyright laws.
 *
 * Neither reproduction or dissemination of this material is permitted without prior written
 * permission from Punch Cyber Analytics Group
 */

package com.punchcyber.pakhet.datatypes.evtx

object MsEventId {
    val event_id_mapping: Map[Int,String] = Map[Int,String](
        4774 -> "An account was mapped for logon.",
        4775 -> "An account could not be mapped for logon.",
        4776 -> "The computer attempted to validate the credentials for an account.",
        4777 -> "The domain controller failed to validate the credentials for an account.",
        4768 -> "A Kerberos authentication ticket (TGT) was requested.",
        4771 -> "Kerberos pre-authentication failed.",
        4772 -> "A Kerberos authentication ticket request failed.",
        4769 -> "A Kerberos service ticket was requested.",
        4770 -> "A Kerberos service ticket was renewed.",
        4773 -> "A Kerberos service ticket request failed.",
        4783 -> "A basic application group was created.",
        4784 -> "A basic application group was changed.",
        4785 -> "A member was added to a basic application group.",
        4786 -> "A member was removed from a basic application group.",
        4787 -> "A non-member was added to a basic application group.",
        4788 -> "A non-member was removed from a basic application group.",
        4789 -> "A basic application group was deleted.",
        4790 -> "An LDAP query group was created.",
        4791 -> "A basic application group was changed.",
        4792 -> "An LDAP query group was deleted.",
        4741 -> "A computer account was created.",
        4742 -> "A computer account was changed.",
        4743 -> "A computer account was deleted.",
        4744 -> "A security-disabled local group was created.",
        4745 -> "A security-disabled local group was changed.",
        4746 -> "A member was added to a security-disabled local group.",
        4747 -> "A member was removed from a security-disabled local group.",
        4748 -> "A security-disabled local group was deleted.",
        4749 -> "A security-disabled global group was created.",
        4750 -> "A security-disabled global group was changed.",
        4751 -> "A member was added to a security-disabled global group.",
        4752 -> "A member was removed from a security-disabled global group.",
        4753 -> "A security-disabled global group was deleted.",
        4759 -> "A security-disabled universal group was created.",
        4760 -> "A security-disabled universal group was changed.",
        4761 -> "A member was added to a security-disabled universal group.",
        4762 -> "A member was removed from a security-disabled universal group.",
        4782 -> "The password hash an account was accessed.",
        4793 -> "The Password Policy Checking API was called.",
        4727 -> "A security-enabled global group was created.",
        4728 -> "A member was added to a security-enabled global group.",
        4729 -> "A member was removed from a security-enabled global group.",
        4730 -> "A security-enabled global group was deleted.",
        4731 -> "A security-enabled local group was created.",
        4732 -> "A member was added to a security-enabled local group.",
        4733 -> "A member was removed from a security-enabled local group.",
        4734 -> "A security-enabled local group was deleted.",
        4735 -> "A security-enabled local group was changed.",
        4737 -> "A security-enabled global group was changed.",
        4754 -> "A security-enabled universal group was created.",
        4755 -> "A security-enabled universal group was changed.",
        4756 -> "A member was added to a security-enabled universal group.",
        4757 -> "A member was removed from a security-enabled universal group.",
        4758 -> "A security-enabled universal group was deleted.",
        4764 -> "A group’s type was changed.",
        4720 -> "A user account was created.",
        4722 -> "A user account was enabled.",
        4723 -> "An attempt was made to change an account's password.",
        4724 -> "An attempt was made to reset an account's password.",
        4725 -> "A user account was disabled.",
        4726 -> "A user account was deleted.",
        4738 -> "A user account was changed.",
        4740 -> "A user account was locked out.",
        4765 -> "SID History was added to an account.",
        4766 -> "An attempt to add SID History to an account failed.",
        4767 -> "A user account was unlocked.",
        4780 -> "The ACL was set on accounts which are members of administrators groups.",
        4781 -> "The name of an account was changed:",
        4794 -> "An attempt was made to set the Directory Services Restore Mode.",
        5376 -> "Credential Manager credentials were backed up.",
        5377 -> "Credential Manager credentials were restored from a backup.",
        4692 -> "Backup of data protection master key was attempted.",
        4693 -> "Recovery of data protection master key was attempted.",
        4694 -> "Protection of auditable protected data was attempted.",
        4695 -> "Unprotection of auditable protected data was attempted.",
        4688 -> "A new process has been created.",
        4696 -> "A primary token was assigned to process.",
        4689 -> "A process has exited.",
        5712 -> "A Remote Procedure Call (RPC) was attempted.",
        4928 -> "An Active Directory replica source naming context was established.",
        4929 -> "An Active Directory replica source naming context was removed.",
        4930 -> "An Active Directory replica source naming context was modified.",
        4931 -> "An Active Directory replica destination naming context was modified.",
        4934 -> "Attributes of an Active Directory object were replicated.",
        4935 -> "Replication failure begins.",
        4936 -> "Replication failure ends.",
        4937 -> "A lingering object was removed from a replica.",
        4662 -> "An operation was performed on an object.",
        5136 -> "A directory service object was modified.",
        5137 -> "A directory service object was created.",
        5138 -> "A directory service object was undeleted.",
        5139 -> "A directory service object was moved.",
        5141 -> "A directory service object was deleted.",
        4932 -> "Synchronization of a replica of an Active Directory naming context has begun.",
        4933 -> "Synchronization of a replica of an Active Directory naming context has ended.",
        4978 -> "During extended mode negotiation, IPsec received an invalid negotiation packet. If this problem persists, it could indicate a network issue or an attempt to modify or replay this negotiation.",
        4979 -> "IPsec main mode and extended mode security associations were established.",
        4980 -> "IPsec main mode and extended mode security associations were established.",
        4981 -> "IPsec main mode and extended mode security associations were established.",
        4982 -> "IPsec main mode and extended mode security associations were established.",
        4983 -> "An IPsec extended mode negotiation failed. The corresponding main mode security association has been deleted.",
        4984 -> "An IPsec extended mode negotiation failed. The corresponding main mode security association has been deleted.",
        4646 -> "IKE DoS-prevention mode started.",
        4650 -> "An IPsec main mode security association was established. Extended mode was not enabled. Certificate authentication was not used.",
        4651 -> "An IPsec main mode security association was established. Extended mode was not enabled. A certificate was used for authentication.",
        4652 -> "An IPsec main mode negotiation failed.",
        4653 -> "An IPsec main mode negotiation failed.",
        4655 -> "An IPsec main mode security association ended.",
        4976 -> "During main mode negotiation, IPsec received an invalid negotiation packet. If this problem persists, it could indicate a network issue or an attempt to modify or replay this negotiation.",
        5049 -> "An IPsec security association was deleted.",
        5453 -> "IPsec Policy Agent applied Active Directory storage IPsec policy on the computer.",
        4654 -> "An IPsec quick mode negotiation failed.",
        4977 -> "During quick mode negotiation, IPsec received an invalid negotiation packet. If this problem persists, it could indicate a network issue or an attempt to modify or replay this negotiation.",
        5451 -> "An IPsec quick mode security association was established.",
        5452 -> "An IPsec quick mode security association ended.",
        4634 -> "An account was logged off.",
        4647 -> "User initiated logoff.",
        4624 -> "An account was successfully logged on.",
        4625 -> "An account failed to log on.",
        4648 -> "A logon was attempted using explicit credentials.",
        4675 -> "SIDs were filtered.",
        6272 -> "Network Policy Server granted access to a user.",
        6273 -> "Network Policy Server denied access to a user.",
        6274 -> "Network Policy Server discarded the request for a user.",
        6275 -> "Network Policy Server discarded the accounting request for a user.",
        6276 -> "Network Policy Server quarantined a user.",
        6277 -> "Network Policy Server granted access to a user but put it on probation because the host did not meet the defined health policy.",
        6278 -> "Network Policy Server granted full access to a user because the host met the defined health policy.",
        6279 -> "Network Policy Server locked the user account due to repeated failed authentication attempts.",
        6280 -> "Network Policy Server unlocked the user account.",
        4649 -> "A replay attack was detected.",
        4778 -> "A session was reconnected to a Window Station.",
        4779 -> "A session was disconnected from a Window Station.",
        4800 -> "The workstation was locked.",
        4801 -> "The workstation was unlocked.",
        4802 -> "The screen saver was invoked.",
        4803 -> "The screen saver was dismissed.",
        5378 -> "The requested credentials delegation was disallowed by policy.",
        5632 -> "A request was made to authenticate to a wireless network.",
        5633 -> "A request was made to authenticate to a wired network.",
        4964 -> "Special groups have been assigned to a new logon.",
        4665 -> "An attempt was made to create an application client context.",
        4666 -> "An application attempted an operation:",
        4667 -> "An application client context was deleted.",
        4668 -> "An application was initialized.",
        4868 -> "The certificate manager denied a pending certificate request.",
        4869 -> "Certificate Services received a resubmitted certificate request.",
        4870 -> "Certificate Services revoked a certificate.",
        4871 -> "Certificate Services received a request to publish the certificate revocation list (CRL).",
        4872 -> "Certificate Services published the certificate revocation list (CRL).",
        4873 -> "A certificate request extension changed.",
        4874 -> "One or more certificate request attributes changed.",
        4875 -> "Certificate Services received a request to shut down.",
        4876 -> "Certificate Services backup started.",
        4877 -> "Certificate Services backup completed.",
        4878 -> "Certificate Services restore started.",
        4879 -> "Certificate Services restore completed.",
        4880 -> "Certificate Services started.",
        4881 -> "Certificate Services stopped.",
        4882 -> "The security permissions for Certificate Services changed.",
        4883 -> "Certificate Services retrieved an archived key.",
        4884 -> "Certificate Services imported a certificate into its database.",
        4885 -> "The audit filter for Certificate Services changed.",
        4886 -> "Certificate Services received a certificate request.",
        4887 -> "Certificate Services approved a certificate request and issued a certificate.",
        4888 -> "Certificate Services denied a certificate request.",
        4889 -> "Certificate Services set the status of a certificate request to pending.",
        4890 -> "The certificate manager settings for Certificate Services changed.",
        4891 -> "A configuration entry changed in Certificate Services.",
        4892 -> "A property of Certificate Services changed.",
        4893 -> "Certificate Services archived a key.",
        4894 -> "Certificate Services imported and archived a key.",
        4895 -> "Certificate Services published the CA certificate to Active Directory Domain Services.",
        4896 -> "One or more rows have been deleted from the certificate database.",
        4897 -> "Role separation enabled:",
        4898 -> "Certificate Services loaded a template.",
        4899 -> "A Certificate Services template was updated.",
        4900 -> "Certificate Services template security was updated.",
        5120 -> "OCSP Responder Service Started.",
        5121 -> "OCSP Responder Service Stopped.",
        5122 -> "A Configuration entry changed in the OCSP Responder Service.",
        5123 -> "A configuration entry changed in the OCSP Responder Service.",
        5124 -> "A security setting was updated on OCSP Responder Service.",
        5125 -> "A request was submitted to OCSP Responder Service.",
        5126 -> "Signing Certificate was automatically updated by the OCSP Responder Service.",
        5127 -> "The OCSP Revocation Provider successfully updated the revocation information.",
        5145 -> "A network share object was checked to see whether the client can be granted desired access.",
        5140 -> "A network share object was accessed.",
        5142 -> "A network share object was added.",
        5143 -> "A network share object was modified.",
        5144 -> "A network share object was deleted.",
        5168 -> "Spn check for SMB/SMB2 failed.",
        4664 -> "An attempt was made to create a hard link.",
        4985 -> "The state of a transaction has changed.",
        5051 -> "A file was virtualized.",
        5031 -> "The Windows Firewall Service blocked an application from accepting incoming connections on the network.",
        5148 -> "The Windows Filtering Platform has detected a DoS attack and entered a defensive mode; packets associated with this attack will be discarded.",
        5149 -> "The DoS attack has subsided and normal processing is being resumed.",
        5150 -> "The Windows Filtering Platform has blocked a packet.",
        5151 -> "A more restrictive Windows Filtering Platform filter has blocked a packet.",
        5154 -> "The Windows Filtering Platform has permitted an application or service to listen on a port for incoming connections.",
        5155 -> "The Windows Filtering Platform has blocked an application or service from listening on a port for incoming connections.",
        5156 -> "The Windows Filtering Platform has permitted a connection.",
        5157 -> "The Windows Filtering Platform has blocked a connection.",
        5158 -> "The Windows Filtering Platform has permitted a bind to a local port.",
        5159 -> "The Windows Filtering Platform has blocked a bind to a local port.",
        5152 -> "The Windows Filtering Platform has blocked a packet.",
        5153 -> "A more restrictive Windows Filtering Platform filter has blocked a packet.",
        4656 -> "A handle to an object was requested.",
        4658 -> "The handle to an object was closed.",
        4690 -> "An attempt was made to duplicate a handle to an object.",
        4671 -> "An application attempted to access a blocked ordinal through the TBS.",
        4691 -> "Indirect access to an object was requested.",
        4698 -> "A scheduled task was created.",
        4699 -> "A scheduled task was deleted.",
        4700 -> "A scheduled task was enabled.",
        4701 -> "A scheduled task was disabled.",
        4702 -> "A scheduled task was updated.",
        4702 -> "A scheduled task was updated.",
        5888 -> "An object in the COM+ Catalog was modified.",
        5889 -> "An object was deleted from the COM+ Catalog.",
        5890 -> "An object was added to the COM+ Catalog.",
        4657 -> "A registry value was modified.",
        5039 -> "A registry key was virtualized.",
        4659 -> "A handle to an object was requested with intent to delete.",
        4660 -> "An object was deleted.",
        4661 -> "A handle to an object was requested.",
        4663 -> "An attempt was made to access an object.",
        4715 -> "The audit policy (SACL) on an object was changed.",
        4719 -> "System audit policy was changed.",
        4817 -> "Auditing settings on an object were changed.",
        4902 -> "The Per-user audit policy table was created.",
        4904 -> "An attempt was made to register a security event source.",
        4905 -> "An attempt was made to unregister a security event source.",
        4906 -> "The CrashOnAuditFail value has changed.",
        4907 -> "Auditing settings on object were changed.",
        4908 -> "Special Groups Logon table modified.",
        4912 -> "Per User Audit Policy was changed.",
        4706 -> "A new trust was created to a domain.",
        4707 -> "A trust to a domain was removed.",
        4713 -> "Kerberos policy was changed.",
        4716 -> "Trusted domain information was modified.",
        4717 -> "System security access was granted to an account.",
        4718 -> "System security access was removed from an account.",
        4739 -> "Domain Policy was changed.",
        4864 -> "A namespace collision was detected.",
        4865 -> "A trusted forest information entry was added.",
        4866 -> "A trusted forest information entry was removed.",
        4867 -> "A trusted forest information entry was modified.",
        4704 -> "A user right was assigned.",
        4705 -> "A user right was removed.",
        4714 -> "Data Recovery Agent group policy for Encrypting File System (EFS) has changed. The new changes have been applied.",
        4709 -> "The IPsec Policy Agent service was started.",
        4710 -> "The IPsec Policy Agent service was disabled.",
        4711 -> "May contain any one of the following: PAStore Engine applied locally cached copy of Active Directory storage IPsec policy on the computer.,PAStore Engine applied Active Directory storage IPsec policy on the computer.,,PAStore Engine failed to apply locally cached copy of Active Directory storage IPsec policy on the computer.,PAStore Engine failed to apply Active Directory storage IPsec policy on the computer.,PAStore Engine failed to apply some rules of the active IPsec policy on the computer.,PAStore Engine failed to load directory storage IPsec policy on the computer.,PAStore Engine failed to load local storage IPsec policy on the computer.,PAStore Engine loaded local storage IPsec policy on the computer.,PAStore Engine polled for changes to the active IPsec policy and detected no changes.",
        4712 -> "IPsec Policy Agent encountered a potentially serious failure.",
        5040 -> "A change was made to IPsec settings. An authentication set was added.",
        5041 -> "A change was made to IPsec settings. An authentication set was modified.",
        5042 -> "A change was made to IPsec settings. An authentication set was deleted.",
        5043 -> "A change was made to IPsec settings. A connection security rule was added.",
        5044 -> "A change was made to IPsec settings. A connection security rule was modified.",
        5045 -> "A change was made to IPsec settings. A connection security rule was deleted.",
        5046 -> "A change was made to IPsec settings. A crypto set was added.",
        5047 -> "A change was made to IPsec settings. A crypto set was modified.",
        5048 -> "A change was made to IPsec settings. A crypto set was deleted.",
        5440 -> "The following callout was present when the Windows Filtering Platform Base Filtering Engine started.",
        5441 -> "The following filter was present when the Windows Filtering Platform Base Filtering Engine started.",
        5442 -> "The following provider was present when the Windows Filtering Platform Base Filtering Engine started.",
        5443 -> "The following provider context was present when the Windows Filtering Platform Base Filtering Engine started.",
        5444 -> "The following sub-layer was present when the Windows Filtering Platform Base Filtering Engine started.",
        5446 -> "A Windows Filtering Platform callout has been changed.",
        5448 -> "A Windows Filtering Platform provider has been changed.",
        5449 -> "A Windows Filtering Platform provider context has been changed.",
        5450 -> "A Windows Filtering Platform sub-layer has been changed.",
        5456 -> "PAStore Engine applied Active Directory storage IPsec policy on the computer.",
        5457 -> "IPsec Policy Agent failed to apply Active Directory storage IPsec policy on the computer.",
        5458 -> "IPsec Policy Agent applied locally cached copy of Active Directory storage IPsec policy on the computer.",
        5459 -> "IPsec Policy Agent failed to apply locally cached copy of Active Directory storage IPsec policy on the computer.",
        5460 -> "IPsec Policy Agent applied local registry storage IPsec policy on the computer.",
        5461 -> "IPsec Policy Agent failed to apply local registry storage IPsec policy on the computer.",
        5462 -> "IPsec Policy Agent failed to apply some rules of the active IPsec policy on the computer. Use the IP Security Monitor snap-in to diagnose the problem.",
        5463 -> "IPsec Policy Agent polled for changes to the active IPsec policy and detected no changes.",
        5464 -> "IPsec Policy Agent polled for changes to the active IPsec policy, detected changes, and applied them.",
        5465 -> "IPsec Policy Agent received a control for forced reloading of IPsec policy and processed the control successfully.",
        5466 -> "IPsec Policy Agent polled for changes to the Active Directory IPsec policy, determined that Active Directory cannot be reached, and will use the cached copy of the Active Directory IPsec policy instead. Any changes made to the Active Directory IPsec policy since the last poll could not be applied.",
        5467 -> "IPsec Policy Agent polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, and found no changes to the policy. The cached copy of the Active Directory IPsec policy is no longer being used.",
        5468 -> "IPsec Policy Agent polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, found changes to the policy, and applied those changes. The cached copy of the Active Directory IPsec policy is no longer being used.",
        5471 -> "IPsec Policy Agent loaded local storage IPsec policy on the computer.",
        5472 -> "IPsec Policy Agent failed to load local storage IPsec policy on the computer.",
        5473 -> "IPsec Policy Agent loaded directory storage IPsec policy on the computer.",
        5474 -> "IPsec Policy Agent failed to load directory storage IPsec policy on the computer.",
        5477 -> "IPsec Policy Agent failed to add quick mode filter.",
        4944 -> "The following policy was active when the Windows Firewall started.",
        4945 -> "A rule was listed when the Windows Firewall started.",
        4946 -> "A change was made to the Windows Firewall exception list. A rule was added.",
        4947 -> "A change was made to the Windows Firewall exception list. A rule was modified.",
        4948 -> "A change was made to the Windows Firewall exception list. A rule was deleted.",
        4949 -> "Windows Firewall settings were restored to the default values.",
        4950 -> "A Windows Firewall setting was changed.",
        4951 -> "Windows Firewall ignored a rule because its major version number is not recognized.",
        4952 -> "Windows Firewall ignored parts of a rule because its minor version number is not recognized. Other parts of the rule will be enforced.",
        4953 -> "Windows Firewall ignored a rule because it could not be parsed.",
        4954 -> "Group Policy settings for Windows Firewall were changed, and the new settings were applied.",
        4956 -> "Windows Firewall changed the active profile.",
        4957 -> "Windows Firewall did not apply the following rule:",
        4958 -> "Windows Firewall did not apply the following rule because the rule referred to items not configured on this computer:",
        5050 -> "An attempt to programmatically disable Windows Firewall using a call to INetFwProfile.FirewallEnabled(FALSE) interface was rejected because this API is not supported on this version of Windows. This is most likely due to a program that is incompatible with this version of Windows. Please contact the program's manufacturer to make sure you have a compatible program version.",
        4909 -> "The local policy settings for the TBS were changed.",
        4910 -> "The group policy settings for the TBS were changed.",
        5063 -> "A cryptographic provider operation was attempted.",
        5064 -> "A cryptographic context operation was attempted.",
        5065 -> "A cryptographic context modification was attempted.",
        5066 -> "A cryptographic function operation was attempted.",
        5067 -> "A cryptographic function modification was attempted.",
        5068 -> "A cryptographic function provider operation was attempted.",
        5069 -> "A cryptographic function property operation was attempted.",
        5070 -> "A cryptographic function property modification was attempted.",
        5447 -> "A Windows Filtering Platform filter has been changed.",
        6144 -> "Security policy in the group policy objects has been applied successfully.",
        6145 -> "One or more errors occurred while processing security policy in the group policy objects.",
        4670 -> "Permissions on an object were changed.",
        4672 -> "Special privileges assigned to new logon.",
        4673 -> "A privileged service was called.",
        4674 -> "An operation was attempted on a privileged object.",
        4960 -> "IPsec dropped an inbound packet that failed an integrity check. If this problem persists, it could indicate a network issue or that packets are being modified in transit to this computer. Verify that the packets sent from the remote computer are the same as those received by this computer. This error might also indicate interoperability problems with other IPsec implementations.",
        4961 -> "IPsec dropped an inbound packet that failed a replay check. If this problem persists, it could indicate a replay attack against this computer.",
        4962 -> "IPsec dropped an inbound packet that failed a replay check. The inbound packet had too low a sequence number to ensure it was not a replay.",
        4963 -> "IPsec dropped an inbound clear text packet that should have been secured. If the remote computer is configured with a Request Outbound IPsec policy, this might be benign and expected. This can also be caused by the remote computer changing its IPsec policy without informing this computer. This could also be a spoofing attack attempt.",
        4965 -> "IPsec received a packet from a remote computer with an incorrect Security Parameter Index (SPI). This is usually caused by malfunctioning hardware that is corrupting packets. If these errors persist, verify that the packets sent from the remote computer are the same as those received by this computer. This error might also indicate interoperability problems with other IPsec implementations. In that case, if connectivity is not impeded, then these events can be ignored.",
        5478 -> "The IPsec Policy Agent service was started.",
        5479 -> "IPsec Services has been shut down successfully. The shutdown of IPsec Services can put the computer at greater risk of network attack or expose the computer to potential security risks.",
        5480 -> "IPsec Policy Agent failed to get the complete list of network interfaces on the computer. This poses a potential security risk because some of the network interfaces may not get the protection provided by the applied IPsec filters. Use the IP Security Monitor snap-in to diagnose the problem.",
        5483 -> "The IPsec Policy Agent service failed to initialize its RPC server. The service could not be started.",
        5484 -> "The IPsec Policy Agent service experienced a critical failure and has shut down. The shutdown of this service can put the computer at greater risk of network attack or expose the computer to potential security risks.",
        5485 -> "IPsec Policy Agent failed to process some IPsec filters on a plug-and-play event for network interfaces. This poses a potential security risk because some of the network interfaces may not get the protection provided by the applied IPsec filters. Use the IP Security Monitor snap-in to diagnose the problem.",
        5024 -> "The Windows Firewall service started successfully.",
        5025 -> "The Windows Firewall service was stopped.",
        5027 -> "The Windows Firewall service was unable to retrieve the security policy from the local storage. Windows Firewall will continue to enforce the current policy.",
        5028 -> "Windows Firewall was unable to parse the new security policy. Windows Firewall will continue to enforce the current policy.",
        5029 -> "The Windows Firewall service failed to initialize the driver. Windows Firewall will continue to enforce the current policy.",
        5030 -> "The Windows Firewall service failed to start.",
        5032 -> "Windows Firewall was unable to notify the user that it blocked an application from accepting incoming connections on the network.",
        5033 -> "The Windows Firewall Driver started successfully.",
        5034 -> "The Windows Firewall Driver was stopped.",
        5035 -> "The Windows Firewall Driver failed to start.",
        5037 -> "The Windows Firewall Driver detected a critical runtime error, terminating.",
        5058 -> "Key file operation.",
        5059 -> "Key migration operation.",
        6400 -> "BranchCache: Received an incorrectly formatted response while discovering availability of content.",
        6401 -> "BranchCache: Received invalid data from a peer. Data discarded.",
        6403 -> "BranchCache: The hosted cache sent an incorrectly formatted response to the client.",
        6404 -> "BranchCache: Hosted cache could not be authenticated using the provisioned SSL certificate.",
        6405 -> "BranchCache: %2 instance(s) of event id %1 occurred.",
        6406 -> "%1 registered to Windows Firewall to control filtering for the following: %2",
        6407 -> "1%",
        4608 -> "Windows is starting up.",
        4616 -> "The system time was changed.",
        4621 -> "Administrator recovered system from CrashOnAuditFail. Users who are not administrators will now be allowed to log on. Some auditable activity might not have been recorded.",
        4610 -> "An authentication package has been loaded by the Local Security Authority.",
        4611 -> "A trusted logon process has been registered with the Local Security Authority.",
        4614 -> "A notification package has been loaded by the Security Account Manager.",
        4622 -> "A security package has been loaded by the Local Security Authority.",
        4697 -> "A service was installed in the system.",
        4612 -> "Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits.",
        4615 -> "Invalid use of LPC port.",
        4618 -> "A monitored security event pattern has occurred.",
        4816 -> "RPC detected an integrity violation while decrypting an incoming message.",
        5038 -> "Code integrity determined that the image hash of a file is not valid. The file could be corrupt due to unauthorized modification or the invalid hash could indicate a potential disk device error.",
        5056 -> "A cryptographic self test was performed.",
        5057 -> "A cryptographic primitive operation failed.",
        5060 -> "Verification operation failed.",
        5061 -> "Cryptographic operation.",
        5062 -> "A kernel-mode cryptographic self test was performed.",
        6281 -> "Code Integrity determined that the page hashes of an image file are not valid. The file could be improperly signed without page hashes or corrupt due to unauthorized modification. The invalid hashes could indicate a potential disk device error"
    )
}